### ISSUE TITLE
Add C docs

### ISSUE THREAD

**Issue by dimonomid** [mongoose-os-libs/prometheus-metrics#1]
@pimvanpelt , could you please add docs to the public header https://github.com/mongoose-os-libs/prometheus-metrics/blob/master/include/mgos_prometheus_metrics.h , so that we'll have them nicely rendered at https://mongoose-os.com/docs/api/mgos_prometheus_metrics.h.html ?

**Comment by pimvanpelt** [comment]
Done in https://github.com/mongoose-os-libs/prometheus-metrics/commit/c965bd5f8ac99e2c2a14dc4e69f168974eb572cd

**Comment by dimonomid** [comment]
Thank you!
